### ISSUE TITLE
does not work under java 8

### ISSUE THREAD

**Issue by gaborbernat** [youribonnaffe/gradle-format-plugin#15]
FAILURE: Build failed with an exception.

* What went wrong:
java.lang.UnsupportedClassVersionError: com/github/youribonnaffe/gradle/format/FormatPlugin : Unsupported major.minor version 52.0
> com/github/youribonnaffe/gradle/format/FormatPlugin : Unsupported major.minor version 52.0

**Comment by youribonnaffe** [comment]
Isn't that kind of error message appearing when you use a JRE <8 with something compiled with Java 8 (which could the case for the plugin) ?

**Comment by jtnelson** [comment]
I'm using Java 7 with gradle and getting this error. Is there a version that is compiled for use against Java 7?

**Comment by youribonnaffe** [comment]
I just published a 1.3 version, compiled with JDK7.
https://plugins.gradle.org/plugin/com.github.youribonnaffe.gradle.format

**Comment by jtnelson** [comment]
Thanks!, its working for me now :)

**Comment by youribonnaffe** [comment]
Good to know, I'll close the issue then :)
