### ISSUE TITLE
Update to more recent eclipse code base?

### ISSUE THREAD

**Issue by igorspasic** [youribonnaffe/gradle-format-plugin#21]

**Comment by youribonnaffe** [comment]
Given the fact it has been a major p*in in the *ss last time I did it (very hard to find out which dependencies you need and they are not really distributed as Maven artifacts), I'm not really motivated to do it my self (also I'm not using the plugin myself so even less motivated :)).

But if you'd like to contribute, you are welcome to send a PR.

**Comment by igorspasic** [comment]
Totally understand what you are talking about ;)

To be honest, I am not a big fan of eclipse formatter, would rather to do the similar with IntelliJ IDEA, it has formatter and re-ordering of the structure...

Thanx!

**Comment by youribonnaffe** [comment]
If the formatter from IntelliJ is somehow usable as a standalone library (a CLI mode would be a good indicator that it is feasible, not sure it exists), it would be possible to use it in the plugin.
My reason for developing the plugin was to reuse an Eclipse configuration file (although we end all using IntelliJ :D).

**Comment by igorspasic** [comment]
Yeah, Ive been asked IntelliJ several times about this and there are feature requests on their board... still nothing: https://youtrack.jetbrains.com/issue/IDEA-99267
