### ISSUE TITLE
Plugin not found in repository

### ISSUE THREAD

**Issue by obecker** [youribonnaffe/gradle-format-plugin#22]
Hi, I just wanted to try out your plugin, but it seems it has disappeared from the plugin repository.

I simply followed your instructions, however, gradle tells me

    > Could not resolve all dependencies for configuration ':classpath'.
       > Could not find com.github.youribonnaffe.gradle.format:gradle-format-plugin:1.3.
         Searched in the following locations:
             https://plugins.gradle.org/m2/com/github/youribonnaffe/gradle/format/gradle-format-plugin/1.3/gradle-format-plugin-1.3.pom
             https://plugins.gradle.org/m2/com/github/youribonnaffe/gradle/format/gradle-format-plugin/1.3/gradle-format-plugin-1.3.jar

When I open one of the URLs in a browser I get

    {
      "errors" : [ {
        "status" : 404,
        "message" : "Could not find resource"
      } ]
    }

Could you please check what's wrong? Thank you.

**Comment by youribonnaffe** [comment]
Hi,
I checked and even tried to publish a version 1.4 version and still 404.
I raised the issue on the Gradle forum (https://discuss.gradle.org/t/404-on-published-plugin/14069)

**Comment by obecker** [comment]
Any news on this issue? Could you perhaps deploy a version to a different repository?
Thanks, Oliver

**Comment by steinsag** [comment]
I'm able to use the plugin as follows:

`plugins {
    id "com.github.youribonnaffe.gradle.format" version "1.4"
}`

**Comment by youribonnaffe** [comment]
Indeed it seems the plugin id format changed, it should be _gradle.plugin.com.github.youribonnaffe.gradle.format:gradle-format-plugin:1.4_ if you are using the `buildscript`block or just use
```
plugins {
  id "com.github.youribonnaffe.gradle.format" version "1.4"
}
```

I've updated the Readme.

Thanks for the feeback @steinsag

**Comment by obecker** [comment]
Thanks, that worked.
