### ISSUE TITLE
import ordering support?

### ISSUE THREAD

**Issue by gaborbernat** [youribonnaffe/gradle-format-plugin#4]
any way to add this too?

**Comment by youribonnaffe** [comment]
Do you know if it is something supported by Eclipse API?
I'm also wondering if those settings can be exported.

**Comment by gaborbernat** [comment]
Well, there is someway to do this. Similar how https://github.com/krasa/EclipseCodeFormatter does it. Maybe we can add it by adding it to the plugin and interacting with the Eclipse formater API?

**Comment by youribonnaffe** [comment]
Indeed it looks like there is a way. I probably won't be able to work on it my self those days but I'll be happy to accept any contribution.

It looks like import order configuration can be exported (https://github.com/krasa/EclipseCodeFormatter/blob/master/test/resources/bcjur2.importorder) then I'm not sure about things like static import, imports layout.

**Comment by youribonnaffe** [comment]
Hi,

I added this feature based on the code from krasa EclipseCodeFormatter. You can try it in this branch https://github.com/youribonnaffe/gradle-format-plugin/tree/import_order

I could not find an easy way to do it using Eclipse's classes as it requires to manipulate Eclipse compilation unit, AST and everything. Krasa's solution is just based on import line (just text parsing).

Let me know if it works for you.

**Comment by gaborbernat** [comment]
Looks great to me, I'll try out next week if you can make a some sort of release for it. We could also support the eclipse import order file format, that would be great :)

**Comment by gaborbernat** [comment]
One more thing is it possible to add empty lines, by specifying an empty string in the order for example?

**Comment by gaborbernat** [comment]
Hello, can you push this in a version?
